config/routes.rb
Rails.application.routes.draw do
  resources :lightsabers
end

app/models/gif.rb
class Gif
  def self.get_random_gif
    [1,2].sample
  end

  def self.give_me_this_gif(id)
    return id
  end
end

app/models/lightsaber.rb
class Lightsaber < ActiveRecord::Base
  validates :owner, presence: true
  validates :color, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lightsabers_controller.rb
class LightsabersController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    @lightsabers = Lightsaber.all
  end

  def new
    @lightsaber = Lightsaber.new
  end

  def create
    @lightsaber = Lightsaber.new(lightsaber_params)
    if @lightsaber.save
      flash[:notice] = "Lightsaber was successfully created"
      redirect_to lightsaber_path(@lightsaber)
    else
      render :new
    end
  end

  def show
    @lightsaber = Lightsaber.find(params[:id])
    @random_gif = Gif.get_random_gif
  end

  def edit
    @lightsaber = Lightsaber.find(params[:id])
  end

  def update
    @lightsaber = Lightsaber.find(params[:id])
      if @lightsaber.update(lightsaber_params)
        flash[:notice] = 'Lightsaber was successfully updated'
        redirect_to lightsabers_path(@lightsaber)
      else
        render :edit
      end
    end

    def destroy
      @lightsaber = Lightsaber.find(params[:id])
      if @lightsaber.destroy
        flash[:notice] = "Lightsaber was destroyed"
        redirect_to lightsabers_path
      end
    end

  private
  def lightsaber_params
    params.require(:lightsaber).permit(:owner, :color)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LightsaberApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= flash[:notice] %>
<hr>
<br>
<%= yield %>

</body>
</html>

app/views/lightsabers/edit.html.erb
<%= form_for @lightsaber do |f| %>
<%= f.label :owner %>
<%= f.text_field :owner %>
<%= f.label :color %>
<%= f.text_field :color %>
<%= f.submit "Update" %>
<% end %>

app/views/lightsabers/index.html.erb
<h1>Lightsabers</h1>

<hr>
<% @lightsabers.each do |lightsaber| %>
Owner:
<%= lightsaber.owner %>
<br>
Color:
<%= lightsaber.color  %>
<br>
<br>
<%= link_to "Edit", edit_lightsaber_path(lightsaber) %>
<%= link_to "Delete", lightsaber_path(lightsaber), method: :delete, data: {confirm: "Are you sure?"} %>
<%= link_to "View", lightsaber_path(lightsaber) %>
<hr>
<% end %>
<%= link_to "New Lightsaber", new_lightsaber_path %>

app/views/lightsabers/new.html.erb
<form action="/lightsabers" class="new_lightsaber" id="new_lightsaber" method="post">
  <label for="lightsaber_owner">Owner</label>:
  <input id="lightsaber_owner" name="lightsaber[owner]" type="text" /><br />

  <label for="lightsaber_color">Color</label>:
  <input id="lightsaber_color" name="lightsaber[color]" type="text" /><br />

  <input name="commit" type="submit" value="Create Lightsaber" />
</form>

<% if @lightsaber.errors.any? %>
  <div class= "error_explanation">
    <ul>
    <% @lightsaber.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

app/views/lightsabers/show.html.erb
Lightsaber:

<%= image_tag("#{@random_gif}.gif") %>
<br>
Owner: <%= @lightsaber.owner %>
<br>
Color: <%= @lightsaber.color %>
<br>
<%= link_to "Edit", edit_lightsaber_path(@lightsaber) %>
<%= link_to "Delete", lightsaber_path(@lightsaber), method: :delete, data: {confirm: "Are you sure?"} %>